name: Build and Push Docker Image
# Pipeline rules
on:
  push:
    branches:
      - main
# GitHub Token Permissions for this workflow
permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    # Which runner to use (equivalent to $APPS_RUNNER_TAG)
    runs-on: ubuntu-latest
    # Environment variable scoped to the job
    env:
      IMAGE: ghcr.io/ableto-gabrielrodriguez/nginx
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Steps are equivalent to script section in GitLab
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: |
          export IMAGE_TAG_BRANCH="${IMAGE}:${GITHUB_REF_NAME}"
          docker build -t "${IMAGE_TAG_BRANCH}" -f Dockerfile .
      - name: Push Docker image
        run: docker push ${IMAGE_TAG_BRANCH}
